Mission7/Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;
namespace Mission7.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket cart;
        public CartSummaryViewComponent(Basket cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Mission7/Views/Shared/ProjectSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book
<div class="card card-outline-primary m-1 p-1 rounded">

    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <span class="badge bg-info" style="float:right">
            Book Classification: @Model.Classification
        </span>
    </div>

    <ul>

        @*<li>Book Title: @b.Title</li>*@
        <li>Book Author: @Model.Author</li>
        <li>Book Publisher: @Model.Publisher</li>
        <li>Book ISBN: @Model.Isbn</li>
        @*<li>Book Classification: @b.Classification</li>*@
        <li>Book Category: @Model.Category</li>
        <li>Book Page Count: @Model.PageCount</li>
        <li>Book Price: @Model.Price</li>
    </ul>

    <form method="post" asp-page="/Donate">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />


        <span class="card-text rounded">
            <button type="submit" class="btn btn-success btn-sm float-right">Add to Cart</button>
        </span>

    </form>

</div>

Mission7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />

</head>
<body>
    @*<div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">Book Project</span>
    </div>*@
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Book Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>

</body>
</html>